### ISSUE TITLE
Crash on Win10 

### ISSUE THREAD

**Issue by Dabako** [b-jesch/script.loungeripper#2]
I am using Win10
Python 3.10
Dependencies are Installed as mentioned in the Description

```
2022-02-08 16:02:10.137 T:6164    ERROR <general>: [script.loungeripper] An error has occurred: Traceback (most recent call last):
                                                     File "D:\Program Files\Kodi\addons\script.loungeripper\default.py", line 503, in <module>
                                                       Ripper.start()
                                                     File "D:\Program Files\Kodi\addons\script.loungeripper\default.py", line 418, in start
                                                       _rv = self.pollSubprocess(self.ripper_executable, self.ripper, self.title)
                                                     File "D:\Program Files\Kodi\addons\script.loungeripper\default.py", line 290, in pollSubprocess
                                                       _comm = subprocess.Popen(process.encode('utf-8'), stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                                     File "D:\Program Files\Kodi\system\python\Lib\subprocess.py", line 854, in __init__
                                                       self._execute_child(args, executable, preexec_fn, close_fds,
                                                     File "D:\Program Files\Kodi\system\python\Lib\subprocess.py", line 1239, in _execute_child
                                                       raise TypeError('bytes args is not allowed on Windows')
                                                   TypeError: bytes args is not allowed on Windows
```

**Comment by b-jesch** [comment]
Since I'm not using Windows (and the exception not occurs on Linux) may I ask you to edit the file "D:\Program Files\Kodi\addons\script.loungeripper\default.py" and try again with the same disc?

If you are able to do this,  change the line 290 (and next line) to:

`        _comm = subprocess.Popen(process.encode('utf-8'), stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                 shell=True, encoding='utf-8', errors='ignore', text=True)`

Simply append ```text=True``` behind the last attribute (don't forget the comma).

Regards

**Comment by b-jesch** [comment]
Closed due no response.

**Comment by Chrisslh** [comment]
Saw this issue at github today - have same on my Windows 10 machine. Line you mentioned on February is already in "default.py", I think: 
`        _comm = subprocess.Popen(process.encode('utf-8'), stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                 shell=True, encoding='utf-8', errors='ignore', text=True)`

Error is still this one:
`[script.loungeripper] An error has occurred: Traceback (most recent call last):
                                                     File "C:\Users\...\AppData\Roaming\Kodi\addons\script.loungeripper\default.py", line 510, in <module>
                                                       Ripper.start()
                                                     File "C:\Users\...\AppData\Roaming\Kodi\addons\script.loungeripper\default.py", line 423, in start
                                                       _rv = self.pollSubprocess(self.ripper_executable, self.ripper, self.title)
                                                     File "C:\Users\...\AppData\Roaming\Kodi\addons\script.loungeripper\default.py", line 291, in pollSubprocess
                                                       _comm = subprocess.Popen(process.encode('utf-8'), stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                                     File "C:\Program Files\Kodi\system\python\Lib\subprocess.py", line 854, in __init__
                                                       self._execute_child(args, executable, preexec_fn, close_fds,
                                                     File "C:\Program Files\Kodi\system\python\Lib\subprocess.py", line 1239, in _execute_child
                                                       raise TypeError('bytes args is not allowed on Windows')
                                                   TypeError: bytes args is not allowed on Windows`

**Comment by b-jesch** [comment]
Yes, I've added this option in hope, that the error has gone. But unfortunately this is not the case.

**Comment by Chrisslh** [comment]
How can I support? Former version with Kodi 18 worked seamless.

**Comment by b-jesch** [comment]
Should run now on both windows and linux with version 3.1.2+matrix...
